name: biocalden_smart_life
description: "Biocalden."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 2.3.3+13

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  permission_handler: ^11.1.0
  qr_code_scanner: ^1.0.1
  flutter_blue_plus: ^1.31.8
  fluttertoast: ^8.2.4
  path_provider: ^2.1.1
  easy_refresh: ^3.3.2+4
  geolocator: ^10.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.3
  workmanager: ^0.5.2
  flutter_email_sender: ^6.0.2
  http: ^1.2.0
  amplify_flutter: ^1.7.0
  amplify_auth_cognito: ^1.7.0
  mqtt_client: ^10.2.0
  provider: ^6.1.2
  firebase_messaging: ^14.7.20
  firebase_core: ^2.27.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  icons_launcher: ^2.1.6


icons_launcher:
  image_path: 'assets/logo_app.png'
  platforms:
    ios:
      enable: true
      image_path: 'assets/logo_app.png'
    android:
      enable: true
      image_path: 'assets/logo_app.png'
      adaptive_background_image: 'assets/bckgr.png'
      adaptive_foreground_image: 'assets/Foreground_CalefactorSmart.png'

flutter:

  uses-material-design: true

  assets:
    - assets/Biocalden/Biocalden_banner.png
    - assets/Biocalden/Corte_laser_negro.png
    - assets/Biocalden/B_negra.png
    - assets/IntelligentGas/IntelligentGasFlyerCL.png
    - assets/IntelligentGas/IntelligentGasFlyerSL.png
    - assets/IntelligentGas/G.png
    - assets/Silema/WB_logo.png
    - assets/Silema/WB_Banner.png
    - assets/Biocalden/BiocaldenBanner.png

  fonts:
    - family:  Bio
      fonts:
        - asset: assets/Icons/Bio/Bio.ttf