name: project_022000iot_user
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0

environment:
  sdk: '>=3.2.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0
  permission_handler: ^11.1.0
  qr_code_scanner: ^1.0.1
  flutter_blue_plus: ^1.31.8
  fluttertoast: ^8.2.4
  path_provider: ^2.1.1
  easy_refresh: ^3.3.2+4
  cloud_firestore: ^4.13.6
  geolocator: ^10.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.3
  workmanager: ^0.5.2
  mqtt_client: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  icons_launcher: ^2.1.6


icons_launcher:
  image_path: 'assets/lg.png'
  platforms:
    android:
      enable: true
      image_path: 'assets/lg.png'
      adaptive_background_image: 'assets/bckgr.png'
      adaptive_foreground_image: 'assets/BiocaldenForegroundWhiteWM2.png'

flutter:

  uses-material-design: true

  assets:
    - assets/google-icon.png
    - assets/Corte_laser_negro.png
    - assets/cert/emqxsl-ca.crt