// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAalsgddUz49N0n3pkvPu7DIDVNwVZWa1E',
    appId: '1:629146285429:web:e43eff8635b2291d690f3c',
    messagingSenderId: '629146285429',
    projectId: 'eiot-2b484',
    authDomain: 'eiot-2b484.firebaseapp.com',
    storageBucket: 'eiot-2b484.appspot.com',
    measurementId: 'G-HLYG1HT7N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN27B6sJr9pQ5NOOiRX_uXk3EP6ZBDjkI',
    appId: '1:629146285429:android:7881f1a638e0c06c690f3c',
    messagingSenderId: '629146285429',
    projectId: 'eiot-2b484',
    storageBucket: 'eiot-2b484.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs9pZwhUpk3YBoW9jcIwN2DXGQjV_1cBA',
    appId: '1:629146285429:ios:aec0aed7e75bd72e690f3c',
    messagingSenderId: '629146285429',
    projectId: 'eiot-2b484',
    storageBucket: 'eiot-2b484.appspot.com',
    iosBundleId: 'com.example.project022000iotUser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs9pZwhUpk3YBoW9jcIwN2DXGQjV_1cBA',
    appId: '1:629146285429:ios:5c7715f14011e5aa690f3c',
    messagingSenderId: '629146285429',
    projectId: 'eiot-2b484',
    storageBucket: 'eiot-2b484.appspot.com',
    iosBundleId: 'com.example.project022000iotUser.RunnerTests',
  );
}
